# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week on Monday
    schedule:
      interval: "weekly"
      day: "monday"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Assign pull requests to specific reviewers
    reviewers:
      - "$GITHUB_REPOSITORY_OWNER"
    # Labels on pull requests for security and dependency updates
    labels:
      - "dependencies"
      - "automated-pr"
    # Specify the target branch to create pull requests against
    target-branch: "main"
    # Allow updates for all dependency types
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Customize commit messages
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "$GITHUB_REPOSITORY_OWNER"
    labels:
      - "dependencies"
      - "automated-pr"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
