name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 1 AM
    - cron: '0 1 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Check for outdated dependencies
        run: npm outdated || true
        
      - name: Create Dependabot PR
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 